<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Testimonial;
use App\Models\Faq;
use App\Models\PageSection;
use App\Models\Setting;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::create([
            'name' => 'Kitsuneoni Admin',
            'email' => 'admin@kitsuneoni.com',
            'password' => Hash::make('password'),
            'role' => 'super_admin',
            'is_active' => true,
        ]);

        $createdCategories = [];
        foreach ([
            ['name' => 'Katanas', 'slug' => 'katanas', 'description' => 'Premium handcrafted Japanese katanas'],
            ['name' => 'Wakizashi', 'slug' => 'wakizashi', 'description' => 'Short Japanese swords'],
            ['name' => 'Tanto', 'slug' => 'tanto', 'description' => 'Japanese short blades'],
            ['name' => 'Display Stands', 'slug' => 'display-stands', 'description' => 'Premium display stands for your collection'],
            ['name' => 'Accessories', 'slug' => 'accessories', 'description' => 'Maintenance oil, cases, and more'],
        ] as $cat) {
            $createdCategories[] = Category::create($cat);
        }

        $brand = Brand::create([
            'name' => 'Kitsuneoni',
            'slug' => 'kitsuneoni',
            'description' => 'Kitsuneoni Workshop — Author\'s workshop specializing in handcrafted Japanese collectibles.',
            'is_active' => true,
        ]);

        // ════════════════════════════════════════════════════════════════
        //  PRODUCTS — Add your products below
        // ════════════════════════════════════════════════════════════════
        //
        //  HOW TO ADD A PRODUCT:
        //  1. Place images in: storage/app/public/products/{product-name}-1.jpg
        //     (use .jpg or .png, name them {product-name}-1, -2, -3, etc.)
        //  2. Place video (optional, compressed) in: storage/app/public/products/videos/{product-name}.mp4
        //  3. Add a product entry to the $products array below
        //  4. Add corresponding image paths to $productImages
        //
        //  VIDEO COMPRESSION (FFmpeg - preserves HD quality):
        //    ffmpeg -i input.mov -c:v libx264 -crf 23 -preset medium -c:a aac -b:a 128k output.mp4
        //    -crf 23 = good quality/size balance (lower = better, 18-28 range)
        //
        //  To seed: php artisan db:seed
        //  To reset: php artisan migrate:fresh --seed
        // ════════════════════════════════════════════════════════════════

        $products = [
            [
                'name' => 'Autumn Dragon',
                'slug' => 'autumn-dragon',
                'short_description' => 'Hand-forged T10 high-carbon steel katana (103 cm) with differential clay tempering and natural wavy hamon. Full tang, hand-polished satin finish. Includes stand, gift case, and maintenance oil.',
                'description' => '<p>The "Autumn Dragon" katana combines traditional Japanese aesthetics with modern craftsmanship. The blade is hand-forged from high-carbon T10 steel and has undergone differential clay tempering, resulting in a natural, wavy hamon pattern on the edge. The blade\'s surface has been hand-polished to a refined satin finish.</p><p>The full-tang construction ensures high strength and reliability. The handle is wrapped in traditional brown ito cord over natural skate leather (same-gawa), providing a secure grip. The tsuba is made of steel with a classic Japanese ornamentation, and the habaki is made of brass with a floral pattern. The scabbard is made of lacquered wood and features a brown sageo cord.</p>',
                'price' => 270,
                'sku' => 'KTN-AD-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => true,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => 'T10 High Carbon Steel',
                'steel_type' => 'T10 High Carbon Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 60,
                'overall_length' => 103,
                'blade_length' => 71,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Natural stingray leather (Samegawa), Brown Ito',
                'scabbard_material' => 'Lacquered wood',
                'weight' => 1300,
                'meta_title' => 'Autumn Dragon Katana — T10 Steel, 103cm | Kitsuneoni',
                'meta_description' => 'Hand-forged T10 steel katana with differential clay tempering and natural wavy hamon. Full tang, 103 cm. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/autumn-dragon.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Black Lotus',
                'slug' => 'black-lotus',
                'short_description' => 'Damascus steel tanto (55 cm) with multi-layered pattern, approx. 60 HRC. Full tang, hand-polished. Includes stand, gift case, and care oil.',
                'description' => '<p>The "Black Lotus" tanto combines traditional Japanese style with modern, hand-forged quality. The blade is made of multi-layered Damascus steel with a striking natural pattern and is hardened to a hardness of approximately 60 HRC, ensuring high strength, excellent wear resistance, and durability.</p><p>The full-tang construction gives the knife superb reliability and balance. The handle is made of wood with a stingray leather-like finish and traditional Japanese braiding. The tsuba is made of iron with an openwork design, and the habaki is made of brass with decorative grooves. The sheath is made of solid wood with a black lacquer finish. Each tanto is hand-assembled.</p>',
                'price' => 215,
                'sku' => 'TNT-BL-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[2]->id,
                'brand_id' => $brand->id,
                'material' => 'Multi-layered Damascus Steel',
                'steel_type' => 'Damascus Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 60,
                'overall_length' => 55,
                'blade_length' => 33,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Faux stingray leather, Traditional Japanese wrapping',
                'scabbard_material' => 'Solid wood, Black lacquer finish',
                'weight' => 720,
                'meta_title' => 'Black Lotus Tanto — Damascus Steel, 55cm | Kitsuneoni',
                'meta_description' => 'Hand-forged Damascus steel tanto with multi-layered pattern. Approx. 60 HRC, full tang, 55 cm. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/black-lotus.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Blue Dragon',
                'slug' => 'blue-dragon',
                'short_description' => 'One-of-a-kind T10 tool steel katana (103 cm) with differential clay tempering, 60 HRC, and mirror polish. Blue dragon engraving on lacquered saya.',
                'description' => '<p>The Blue Dragon is a one-of-a-kind auction-grade katana, crafted separately from the main collection with individual hand-finishing and additional quality control. The blade is hand-forged from T10 tool steel with differential clay tempering, achieving a cutting edge hardness of 60 HRC with a natural wavy hamon. Hand-polished to a mirror finish.</p><p>The tsuba features openwork design in nickel silver (white copper) with a decorative finish. The tsuka is wrapped in blue cotton cord over natural stingray leather with decorative menuki. The saya is crafted from hard mountain wood with multi-layered black lacquer and an artistic engraving of a blue dragon. All fittings are brass with a decorative antique gold finish.</p>',
                'price' => 860,
                'sku' => 'KTN-BD-001',
                'stock' => 1,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => 'T10 Tool Steel',
                'steel_type' => 'T10 Tool Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 60,
                'overall_length' => 103,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Natural stingray leather, Blue cotton wrapping, Decorative menuki',
                'scabbard_material' => 'Hard mountain wood, Multi-layered black lacquer, Blue dragon engraving',
                'weight' => 1100,
                'meta_title' => 'Blue Dragon Katana — One-of-a-Kind T10 Steel | Kitsuneoni',
                'meta_description' => 'One-of-a-kind T10 tool steel katana with blue dragon saya engraving. 60 HRC, mirror polish, 103 cm. Premium collectible with wooden case and stand.',
                'video_url' => '',
                'video_file' => 'products/videos/blue-dragon.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Dragonfly',
                'slug' => 'dragonfly',
                'short_description' => 'T10 high-carbon steel tanto (55 cm) with differential clay tempering and natural hamon. Hand-polished, brass habaki, brown ito wrapping.',
                'description' => '<p>The Yamagata "Dragonfly" Tanto is a compact Japanese blade crafted in the traditional style. The blade is handcrafted from high-carbon T10 steel and has undergone differential clay-hardened tempering, which creates a natural hamon line on the blade. Hand polishing accentuates the blade\'s geometry and its mirror-like shine.</p><p>The handle is wrapped in traditional brown ito cord over natural skate leather (same-gawa). The tsuba and decorative fittings are made of zinc alloy with golden dragonfly motifs. The scabbard is made of lacquered natural wood with an artistic black-and-gold pattern and is complemented by a brown sageo cord.</p>',
                'price' => 420,
                'sku' => 'TNT-DF-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[2]->id,
                'brand_id' => $brand->id,
                'material' => 'T10 High Carbon Steel',
                'steel_type' => 'T10 High Carbon Steel',
                'construction' => 'Full Tang',
                'overall_length' => 55,
                'blade_length' => 33,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Natural stingray leather (Samegawa), Brown Ito',
                'scabbard_material' => 'Lacquered wood',
                'weight' => 650,
                'meta_title' => 'Dragonfly Tanto — T10 Steel, 55cm | Kitsuneoni',
                'meta_description' => 'T10 high-carbon steel tanto with differential clay tempering and natural hamon. 55 cm, hand-polished, premium collectible.',
                'video_url' => '',
                'video_file' => 'products/videos/dragonfly.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Forest Spirit',
                'slug' => 'forest-spirit',
                'short_description' => 'Multi-layered Damascus steel tanto (53 cm) with green lacquered sheath and decorative metal fittings. Hand-forged and hand-polished.',
                'description' => '<p>The "Forest Spirit" tanto is crafted in the traditional Japanese style with striking green lacquered sheaths and decorative metal fittings. The blade is made of multi-layered Damascus steel using a hand-forging method; it features a natural pattern and is characterized by high strength, excellent edge retention, and durability.</p><p>The handle is made of wood with a stingray leather-like finish and traditional Japanese wrapping. The tsuba is made of a decorative metal alloy with a classic ornamentation, and the habaki is adorned with a relief pattern. The scabbard is made of solid wood with a green lacquer finish and decorative carving. Each tanto is assembled by hand.</p>',
                'price' => 225,
                'sku' => 'TNT-FS-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[2]->id,
                'brand_id' => $brand->id,
                'material' => 'Multi-layered Damascus Steel',
                'steel_type' => 'Damascus Steel',
                'construction' => 'Full Tang',
                'overall_length' => 53,
                'blade_length' => 33,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Imitation stingray leather, Traditional Japanese wrapping',
                'scabbard_material' => 'Solid wood, Green lacquer finish with decorative ornamentation',
                'weight' => 600,
                'meta_title' => 'Forest Spirit Tanto — Damascus Steel, 53cm | Kitsuneoni',
                'meta_description' => 'Hand-forged Damascus steel tanto with green lacquered sheath. 53 cm, hand-polished, premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/forest-spirit.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Kokuryū Tantō',
                'slug' => 'kokuryu-tanto',
                'short_description' => 'Multi-layered Damascus steel tantō (55 cm) with artistic dragon tsuba. ~60 HRC, hand-polished, black braided wrap. Includes stand and gift box.',
                'description' => '<p>The Yamagata Kokuryū Tantō is a compact Japanese sword that combines traditional aesthetics with exceptional durability. The blade is crafted from multi-layered Damascus steel that has undergone repeated forging, resulting in a hardness of approximately 60 HRC, high elasticity, and a distinctive steel pattern. The full-tang construction ensures reliability and durability.</p><p>The handle is made of wood with natural stingray leather and traditional black braiding. The tsuba is made of metal and features an artistic depiction of a dragon. The scabbard is crafted from solid wood with black-and-red lacquered carvings and decorative cord. Entirely hand-assembled.</p>',
                'price' => 255,
                'sku' => 'TNT-KT-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[2]->id,
                'brand_id' => $brand->id,
                'material' => 'Multi-layered Damascus Steel',
                'steel_type' => 'Damascus Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 60,
                'overall_length' => 55,
                'blade_length' => 33,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Genuine stingray leather, Black braided wrap',
                'scabbard_material' => 'Solid wood, Black-and-red lacquered carvings',
                'weight' => 760,
                'meta_title' => 'Kokuryū Tantō — Damascus Steel, 55cm | Kitsuneoni',
                'meta_description' => 'Hand-forged Damascus steel tantō with artistic dragon tsuba. ~60 HRC, 55 cm, hand-polished. Premium collectible with stand and gift box.',
                'video_url' => '',
                'video_file' => 'products/videos/kokuryu-tanto.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Muichiro Tokito (Nichirin) Katana',
                'slug' => 'muichiro-tokito-nichirin',
                'short_description' => 'Demon Slayer-inspired katana (105 cm) with matte black blade, geometric gold tsuba, and blue diamond handle pattern. 1045 carbon steel.',
                'description' => '<p>The Muichiro Tokito katana is modeled after the legendary "Pillar of Mist" sword from the anime Demon Slayer. This model faithfully replicates the signature design of the original weapon: a matte black blade, a geometric gold tsuba, a handle with traditional black wrapping and blue diamond patterns, and a classic black wooden scabbard with gold-plated fittings.</p><p>The blade is made of 1045 carbon steel with a decorative surface finish. The full-tang construction ensures strength and reliability. The tsuba is made of a metal alloy, and the habaki has a brass coating. The handle is made of wood with traditional Japanese wrapping, and the scabbard is made of solid wood with a matte black lacquer finish. Each katana is assembled by hand.</p>',
                'price' => 230,
                'sku' => 'KTN-MT-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1045 Carbon Steel',
                'steel_type' => '1045 Carbon Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 53,
                'overall_length' => 105,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Faux stingray leather, Traditional Japanese wrapping',
                'scabbard_material' => 'Solid wood, Matte black lacquer finish',
                'weight' => 950,
                'meta_title' => 'Muichiro Tokito (Nichirin) Katana — 105cm | Kitsuneoni',
                'meta_description' => 'Demon Slayer-inspired Muichiro Tokito katana. 1045 carbon steel, full tang, 105 cm. Premium collectible with stand and gift box.',
                'video_url' => '',
                'video_file' => 'products/videos/muichiro-tokito-nichirin.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Sea Breeze',
                'slug' => 'sea-breeze',
                'short_description' => 'T10 steel katana (102 cm) with differential clay tempering and straight hamon. Hand-engraved dragon motifs, dark blue wrapping. Premium collectible.',
                'description' => '<p>The "Sea Breeze" katana is inspired by the tranquility of the ocean and Japanese sword-making tradition. The blade is crafted from high-quality T10 steel with differential clay-tempering and a straight hamon line. The blade\'s surface is adorned with hand-engraved dragon motifs and polished by hand.</p><p>The full-tang construction ensures high strength and excellent balance. The handle is made of wood, covered with genuine stingray leather, and wrapped in dark blue cord. The habaki is made of brass with embossed dragon engraving. The tsuba is made of iron, and the fittings are made of iron and a zinc alloy. The scabbard is made of solid wood with a lacquer finish. Hand-assembled.</p>',
                'price' => 506,
                'sku' => 'KTN-SB-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => 'T10 Steel',
                'steel_type' => 'T10 Steel',
                'construction' => 'Full Tang',
                'overall_length' => 102,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Genuine stingray leather, Dark blue wrapping',
                'scabbard_material' => 'Solid wood, Lacquer finish',
                'weight' => 1100,
                'meta_title' => 'Sea Breeze Katana — T10 Steel, 102cm | Kitsuneoni',
                'meta_description' => 'T10 steel katana with hand-engraved dragon motifs and straight hamon. 102 cm, full tang, premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/sea-breeze.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Steel Storm',
                'slug' => 'steel-storm',
                'short_description' => 'Multi-layered Damascus steel katana (103.5 cm) with all-metal hilt and scabbard. Solid-forged construction, hand-polished, 1.4 kg.',
                'description' => '<p>The "Steel Storm" katana combines a minimalist, modern design with traditional Japanese craftsmanship. The blade is made of multi-layered Damascus steel with a striking pattern across its entire surface and is forged as a single, solid piece. The all-metal hilt is decorated with embossed ornamentation and ensures high durability.</p><p>The scabbard is made of metal with a wear-resistant lacquer coating. The habaki is made of brass, while the tsuba and all other fittings are made of a metal alloy. The sword is entirely hand-assembled.</p>',
                'price' => 305,
                'sku' => 'KTN-SS-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => 'Multi-layered Damascus Steel',
                'steel_type' => 'Damascus Steel',
                'construction' => 'Full Tang',
                'overall_length' => 103.5,
                'blade_length' => 65.5,
                'blade_width' => 3.2,
                'handle_material' => 'All-metal, cast with embossed ornamentation',
                'scabbard_material' => 'All-metal, painted with wear-resistant lacquer',
                'weight' => 1400,
                'meta_title' => 'Steel Storm Katana — Damascus Steel, 103.5cm | Kitsuneoni',
                'meta_description' => 'Multi-layered Damascus steel katana with all-metal hilt and scabbard. 103.5 cm, solid-forged, premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => null,
                'sales_count' => 0,
            ],
            [
                'name' => "Tanjiro Kamado's Katana",
                'slug' => 'tanjiro-kamados-katana',
                'short_description' => 'Demon Slayer-inspired katana (105 cm) with decorative 1045 carbon steel blade. Red handle wrap, black scabbard. Full tang.',
                'description' => '<p>The Tanjiro Kamado Katana (#1) is modeled after the main character\'s first sword from the anime Demon Slayer. The blade is made of 1045 carbon steel with a decorative surface finish. The full-tang construction ensures strength and durability.</p><p>The tsuba is made of a metal alloy, and the habaki has a brass coating. The handle is made of wood with red stingray leather imitation and traditional Japanese wrapping. The scabbard is made of solid wood with a matte black finish. Each katana is assembled by hand.</p>',
                'price' => 230,
                'sku' => 'KTN-TK-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1045 Carbon Steel',
                'steel_type' => '1045 Carbon Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 53,
                'overall_length' => 105,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Red stingray leather imitation, Traditional Japanese wrapping',
                'scabbard_material' => 'Solid wood, Matte black finish',
                'weight' => 950,
                'meta_title' => "Tanjiro Kamado's Katana — 105cm | Kitsuneoni",
                'meta_description' => 'Demon Slayer Tanjiro Kamado katana replica. 1045 carbon steel, full tang, 105 cm. Premium collectible with stand and gift box.',
                'video_url' => '',
                'video_file' => 'products/videos/tanjiro-kamado.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'The Wandering Warrior',
                'slug' => 'the-wandering-warrior',
                'short_description' => 'T10 high-carbon steel ko-tanto (51 cm) with differential clay tempering and wavy hamon. Solid ebony handle and sheath, brass fittings.',
                'description' => '<p>The "Wandering Warrior" tanto is crafted in the classic Japanese style and combines traditional aesthetics with high-quality craftsmanship. The blade is made of high-carbon T10 steel and has undergone differential clay tempering, resulting in a distinctive wavy hamon pattern on the edge. The blade is hand-polished to a satin finish.</p><p>The full-tang construction ensures the knife\'s strength and durability. The handle is crafted from solid ebony without traditional wrapping, emphasizing the model\'s minimalist style. The habaki and decorative fittings are made of brass. The sheath is also crafted from solid ebony and features a black sageo cord. Each piece is assembled by hand.</p>',
                'price' => 355,
                'sku' => 'TNT-WW-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[2]->id,
                'brand_id' => $brand->id,
                'material' => 'T10 High Carbon Steel',
                'steel_type' => 'T10 High Carbon Steel',
                'construction' => 'Full Tang',
                'overall_length' => 51,
                'blade_length' => 33,
                'blade_width' => 3.2,
                'handle_material' => 'Solid ebony',
                'scabbard_material' => 'Solid ebony',
                'weight' => 550,
                'meta_title' => 'The Wandering Warrior Tanto — T10 Steel, 51cm | Kitsuneoni',
                'meta_description' => 'T10 high-carbon steel ko-tanto with ebony handle and sheath. 51 cm, wavy hamon, hand-polished. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/the-wandering-warrior.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Winged Hawk',
                'slug' => 'winged-hawk',
                'short_description' => '1060 high-carbon steel tachi (103.5 cm) with oil quenching and hand-polished finish. White-lacquered sheath, black traditional braiding.',
                'description' => '<p>The "Winged Hawk" Tachi is crafted in the classic Japanese style and combines historical aesthetics with a reliable modern design. The blade is made of high-carbon 1060 steel, oil-hardened, and hand-polished, giving it excellent strength, elasticity, and precise geometry.</p><p>The full-tang construction ensures high reliability and proper balance. The handle is made of wood, covered with natural stingray leather, and wrapped in traditional black cord. The habaki is made of brass, while the tsuba and decorative fittings are made of zinc alloy with an artistic finish. The white-lacquered sheath, crafted from solid wood, is complemented by a traditional tachi suspension. Each piece is hand-assembled.</p>',
                'price' => 305,
                'sku' => 'TCH-WH-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1060 High Carbon Steel',
                'steel_type' => '1060 High Carbon Steel',
                'construction' => 'Full Tang',
                'overall_length' => 103.5,
                'blade_length' => 72.5,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Natural stingray leather, Black traditional braiding',
                'scabbard_material' => 'Solid wood, White lacquer finish',
                'weight' => 1100,
                'meta_title' => 'Winged Hawk Tachi — 1060 Steel, 103.5cm | Kitsuneoni',
                'meta_description' => '1060 high-carbon steel tachi with white-lacquered sheath. 103.5 cm, oil-hardened, hand-polished. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => null,
                'sales_count' => 0,
            ],
            [
                'name' => 'Sanemi Shinazugawa Katana',
                'slug' => 'sanemi-shinazugawa-katana',
                'short_description' => 'Demon Slayer-inspired katana (105 cm) with black blade with green wave pattern. 1045 carbon steel, full tang. Includes stand and gift case.',
                'description' => '<p>The Sanemi Shinazugawa katana is modeled after the Wind Pillar\'s weapon from the anime "Demon Slayer." The model features a black blade with a green wavy pattern along the cutting edge, black wooden scabbard with a white camouflage pattern, and the signature eight-spoked tsuba.</p><p>The handle is made of wood with traditional Japanese wrapping in a white-and-green color scheme. The blade is crafted from 1045 carbon steel with a decorative surface finish. The full-tang construction ensures durability, and each katana is assembled by hand.</p>',
                'price' => 230,
                'sku' => 'KTN-SS-002',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1045 Carbon Steel',
                'steel_type' => '1045 Carbon Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 53,
                'overall_length' => 105,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Traditional Japanese wrapping, White-and-green scheme',
                'scabbard_material' => 'Solid wood, Decorative finish with white camouflage pattern',
                'weight' => 950,
                'meta_title' => 'Sanemi Shinazugawa Katana — 105cm | Kitsuneoni',
                'meta_description' => 'Demon Slayer Sanemi Shinazugawa katana replica. 1045 carbon steel, full tang, 105 cm. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/sanemi-shinazugawa.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Kokushibo Katana',
                'slug' => 'kokushibo-katana',
                'short_description' => 'Demon Slayer-inspired katana (105 cm) with multi-eye blade pattern, pink scabbard, and purple tsuba. 1045 carbon steel, full tang.',
                'description' => '<p>The Kokushibo katana is modeled after the legendary demonic sword of Upper Moon I from the anime "Demon Slayer." The model combines a recognizable blade with a decorative pattern of multiple eyes, a pink wooden scabbard featuring the brand\'s signature ornamentation, a purple sculpted tsuba, and a handle with dark green traditional Japanese wrapping.</p><p>Underneath the wrapping is a pink imitation stingray leather inlay, giving the handle its distinctive appearance. The blade is made of 1045 carbon steel with a decorative surface finish. The full-tang construction ensures strength and reliability. Each katana is assembled by hand.</p>',
                'price' => 230,
                'sku' => 'KTN-KK-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1045 Carbon Steel',
                'steel_type' => '1045 Carbon Steel',
                'construction' => 'Full Tang',
                'hardness_hrc' => 53,
                'overall_length' => 105,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Pink stingray leather imitation, Dark green traditional wrapping',
                'scabbard_material' => 'Solid wood, Decorative finish',
                'weight' => 950,
                'meta_title' => 'Kokushibo Katana — 105cm | Kitsuneoni',
                'meta_description' => 'Demon Slayer Kokushibo katana replica with eye pattern blade. 1045 carbon steel, full tang, 105 cm. Premium collectible with stand and gift case.',
                'video_url' => '',
                'video_file' => 'products/videos/kokushibo.mp4',
                'sales_count' => 0,
            ],
            [
                'name' => 'Yoriichi Tsugikuni Katana',
                'slug' => 'yoriichi-tsugikuni-katana',
                'short_description' => 'Demon Slayer-inspired katana (105 cm) with black blade with fiery red pattern. 1045 carbon steel, full tang, gold-plated fittings.',
                'description' => '<p>The Yoriichi Tsugikuni Katana is modeled after the legendary sword of the universe\'s greatest swordsman, "The Blade That Slays Demons." This model faithfully reproduces the distinctive appearance of the original blade: a black blade with a fiery red pattern, a sleek black saya with gold-plated fittings, and a handle wrapped in traditional light-gold cord.</p><p>The blade is made of 1045 carbon steel with a decorative surface finish. The guard is made of a metal alloy, and the habaki has a brass coating. The handle is made of wood with traditional Japanese wrapping, and the scabbard is made of solid wood with a matte black lacquer finish. Each katana is assembled by hand.</p>',
                'price' => 230,
                'sku' => 'KTN-YT-001',
                'stock' => 10,
                'is_featured' => true,
                'is_bestseller' => false,
                'is_new' => true,
                'category_id' => $createdCategories[0]->id,
                'brand_id' => $brand->id,
                'material' => '1045 Carbon Steel',
                'steel_type' => '1045 Carbon Steel',
                'construction' => 'Full Tang',
                'overall_length' => 105,
                'blade_length' => 72,
                'blade_width' => 3.2,
                'handle_material' => 'Wood, Traditional Japanese wrapping, Light-gold cord',
                'scabbard_material' => 'Solid wood, Matte black lacquer finish with gold-plated fittings',
                'weight' => 950,
                'meta_title' => 'Yoriichi Tsugikuni Katana — 105cm | Kitsuneoni',
                'meta_description' => 'Demon Slayer Yoriichi Tsugikuni katana replica with fiery red blade pattern. 1045 carbon steel, full tang, 105 cm. Premium collectible with stand and gift box.',
                'video_url' => '',
                'video_file' => 'products/videos/yoriichi-tsugikuni.mp4',
                'sales_count' => 0,
            ],
        ];

        $productImages = [
            0 => ['products/autumn-dragon-1.jpg', 'products/autumn-dragon-2.jpg', 'products/autumn-dragon-3.jpg', 'products/autumn-dragon-4.jpg', 'products/autumn-dragon-5.jpg', 'products/autumn-dragon-6.jpg', 'products/autumn-dragon-7.jpg', 'products/autumn-dragon-8.jpg', 'products/autumn-dragon-9.jpg'],
            1 => ['products/black-lotus-1.jpg', 'products/black-lotus-2.jpg', 'products/black-lotus-3.jpg', 'products/black-lotus-4.jpg', 'products/black-lotus-5.jpg', 'products/black-lotus-6.jpg', 'products/black-lotus-7.jpg', 'products/black-lotus-8.jpg', 'products/black-lotus-9.jpg'],
            2 => ['products/blue-dragon-1.jpg', 'products/blue-dragon-2.jpg', 'products/blue-dragon-3.jpg', 'products/blue-dragon-4.jpg', 'products/blue-dragon-5.jpg', 'products/blue-dragon-6.jpg', 'products/blue-dragon-7.jpg', 'products/blue-dragon-8.jpg'],
            3 => ['products/dragonfly-1.jpg', 'products/dragonfly-2.jpg', 'products/dragonfly-3.jpg', 'products/dragonfly-4.jpg', 'products/dragonfly-5.jpg', 'products/dragonfly-6.jpg', 'products/dragonfly-7.jpg', 'products/dragonfly-8.jpg', 'products/dragonfly-9.jpg', 'products/dragonfly-10.jpg'],
            4 => ['products/forest-spirit-1.jpg', 'products/forest-spirit-2.jpg', 'products/forest-spirit-3.jpg', 'products/forest-spirit-4.jpg', 'products/forest-spirit-5.jpg', 'products/forest-spirit-6.jpg', 'products/forest-spirit-7.jpg', 'products/forest-spirit-8.jpg', 'products/forest-spirit-9.jpg'],
            5 => ['products/kokuryu-tanto-1.jpg', 'products/kokuryu-tanto-2.jpg', 'products/kokuryu-tanto-3.jpg', 'products/kokuryu-tanto-4.jpg', 'products/kokuryu-tanto-5.jpg', 'products/kokuryu-tanto-6.jpg', 'products/kokuryu-tanto-7.jpg', 'products/kokuryu-tanto-8.jpg', 'products/kokuryu-tanto-9.jpg'],
            6 => ['products/muichiro-tokito-nichirin-1.jpg', 'products/muichiro-tokito-nichirin-2.jpg', 'products/muichiro-tokito-nichirin-3.jpg', 'products/muichiro-tokito-nichirin-4.jpg', 'products/muichiro-tokito-nichirin-5.jpg', 'products/muichiro-tokito-nichirin-6.jpg', 'products/muichiro-tokito-nichirin-7.jpg', 'products/muichiro-tokito-nichirin-8.jpg', 'products/muichiro-tokito-nichirin-9.jpg'],
            7 => ['products/sea-breeze-1.jpg', 'products/sea-breeze-2.jpg', 'products/sea-breeze-3.jpg', 'products/sea-breeze-4.jpg', 'products/sea-breeze-5.jpg', 'products/sea-breeze-6.jpg', 'products/sea-breeze-7.jpg', 'products/sea-breeze-8.jpg', 'products/sea-breeze-9.jpg'],
            8 => ['products/steel-storm-1.jpg', 'products/steel-storm-2.jpg', 'products/steel-storm-3.jpg', 'products/steel-storm-4.jpg', 'products/steel-storm-5.jpg', 'products/steel-storm-6.jpg', 'products/steel-storm-7.jpg', 'products/steel-storm-8.jpg', 'products/steel-storm-9.jpg', 'products/steel-storm-10.jpg'],
            9 => ['products/tanjiro-kamado-1.jpg', 'products/tanjiro-kamado-2.jpg', 'products/tanjiro-kamado-3.jpg', 'products/tanjiro-kamado-4.jpg', 'products/tanjiro-kamado-5.jpg', 'products/tanjiro-kamado-6.jpg', 'products/tanjiro-kamado-7.jpg', 'products/tanjiro-kamado-8.jpg', 'products/tanjiro-kamado-9.jpg'],
            10 => ['products/the-wandering-warrior-1.jpg', 'products/the-wandering-warrior-2.jpg', 'products/the-wandering-warrior-3.jpg', 'products/the-wandering-warrior-4.jpg', 'products/the-wandering-warrior-5.jpg', 'products/the-wandering-warrior-6.jpg', 'products/the-wandering-warrior-7.jpg', 'products/the-wandering-warrior-8.jpg', 'products/the-wandering-warrior-9.jpg'],
            11 => ['products/winged-hawk-1.jpg', 'products/winged-hawk-2.jpg', 'products/winged-hawk-3.jpg', 'products/winged-hawk-4.jpg', 'products/winged-hawk-5.jpg', 'products/winged-hawk-6.jpg', 'products/winged-hawk-7.jpg', 'products/winged-hawk-8.jpg', 'products/winged-hawk-9.jpg', 'products/winged-hawk-10.jpg'],
            12 => ['products/sanemi-shinazugawa-1.jpg', 'products/sanemi-shinazugawa-2.jpg', 'products/sanemi-shinazugawa-3.jpg', 'products/sanemi-shinazugawa-4.jpg', 'products/sanemi-shinazugawa-5.jpg', 'products/sanemi-shinazugawa-6.jpg', 'products/sanemi-shinazugawa-7.jpg', 'products/sanemi-shinazugawa-8.jpg'],
            13 => ['products/kokushibo-1.jpg', 'products/kokushibo-2.jpg', 'products/kokushibo-3.jpg', 'products/kokushibo-4.jpg', 'products/kokushibo-5.jpg', 'products/kokushibo-6.jpg', 'products/kokushibo-7.jpg', 'products/kokushibo-8.jpg', 'products/kokushibo-9.jpg'],
            14 => ['products/yoriichi-tsugikuni-1.jpg', 'products/yoriichi-tsugikuni-2.jpg', 'products/yoriichi-tsugikuni-3.jpg', 'products/yoriichi-tsugikuni-4.jpg', 'products/yoriichi-tsugikuni-5.jpg', 'products/yoriichi-tsugikuni-6.jpg', 'products/yoriichi-tsugikuni-7.jpg', 'products/yoriichi-tsugikuni-8.jpg'],
        ];

        foreach ($products as $index => $pData) {
            $product = Product::create($pData);
            foreach ($productImages[$index] ?? [] as $sortOrder => $path) {
                ProductImage::create([
                    'product_id' => $product->id,
                    'path' => $path,
                    'alt_text' => $product->name,
                    'sort_order' => $sortOrder,
                    'is_primary' => $sortOrder === 0,
                ]);
            }
            echo "  Seeded: {$product->name}\n";
        }

        // ════════════════════════════════════════════════════════════════
        //  STATIC DATA (no changes needed)
        // ════════════════════════════════════════════════════════════════
        foreach ([
            ['customer_name' => 'Alex M.', 'customer_title' => 'Collector, USA', 'body' => 'Stunning craftsmanship. Every piece feels like it was made just for you.', 'rating' => 5, 'is_featured' => true],
            ['customer_name' => 'Dmitry K.', 'customer_title' => 'Collector, Russia', 'body' => 'The quality, the packaging, the personal touch — it\'s all there. Highly recommend.', 'rating' => 5, 'is_featured' => true],
            ['customer_name' => 'Marco R.', 'customer_title' => 'Collector, Italy', 'body' => 'Fast delivery to Europe. The craftsmanship rivals pieces I\'ve seen for twice the price.', 'rating' => 5, 'is_featured' => true],
        ] as $tData) {
            Testimonial::create($tData);
        }

        foreach ([
            ['question' => 'How do I place an order?', 'answer' => 'Click "Order Now" on any product page, fill in your details, and submit. We\'ll confirm via email and provide payment details through Telegram or WhatsApp.', 'sort_order' => 1],
            ['question' => 'How long does shipping take?', 'answer' => '<strong>CIS countries:</strong> 3-7 business days via CDEK, Russian Post, or Yandex Delivery.<br><strong>International:</strong> 7-21 business days via DHL or UPS.', 'sort_order' => 2],
            ['question' => 'Are the products handmade?', 'answer' => 'Yes! Every piece is handcrafted in our workshop. Slight variations may occur — this confirms authenticity.', 'sort_order' => 3],
            ['question' => 'What payment methods do you accept?', 'answer' => 'We use a manual order system. After placing your order, we\'ll confirm and provide payment options via Telegram or WhatsApp.', 'sort_order' => 4],
            ['question' => 'Can I track my order?', 'answer' => 'Yes! Once shipped, you\'ll receive a tracking number via email.', 'sort_order' => 5],
            ['question' => 'Do you offer custom pieces?', 'answer' => 'Absolutely! Contact us via Telegram to discuss custom orders.', 'sort_order' => 6],
            ['question' => 'What is included with each order?', 'answer' => 'The product, a premium gift case, display stand (where applicable), and maintenance oil.', 'sort_order' => 7],
            ['question' => 'Do you have a loyalty program?', 'answer' => 'Yes! Bronze (3% after 1 order), Silver (5% after 3 orders), Gold (10% after 5 orders). Your level is permanent.', 'sort_order' => 8],
        ] as $fData) {
            Faq::create($fData);
        }

        PageSection::create(['key' => 'hero_title', 'content' => 'Each Blade Tells a Story']);
        PageSection::create(['key' => 'hero_subtitle', 'content' => 'Premium Japanese collectibles forged by hand with centuries of tradition.']);

        Setting::set('site_name', 'Kitsuneoni');
        Setting::set('site_tagline', 'Premium Handcrafted Japanese Collectibles');
        Setting::set('contact_email', 'orders@kitsuneoni.com');
    }
}
